"""
Structured LLM Reasoning, Scientific Hypothesis Generation & Multi-Agent Critique
==================================================================================
Implements structured hypothesis generation, multi-agent critique, arbitration,
and JSON schema enforcement for neuro-symbolic scientific model selection.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class CandidateRanking(BaseModel):
    model_name: str
    aic: float
    r_squared: float
    plausibility_score: float = Field(..., ge=0.0, le=1.0)
    primary_limitation_or_strength: str


class ModelHypothesis(BaseModel):
    """Structured hypothesis payload generated by the primary reasoning agent."""
    selected_model: str
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    mechanistic_rationale: str
    temporal_features_analyzed: List[str]
    cited_parameters: Dict[str, float]
    candidate_rankings: List[CandidateRanking]
    biological_interpretation: str


class CritiqueReport(BaseModel):
    """Adversarial critique generated to scrutinize the proposed model hypothesis."""
    critique_score: float = Field(..., ge=0.0, le=1.0, description="Overall plausibility rating (1.0 = flawless)")
    strengths: List[str]
    potential_flaws_or_hallucinations: List[str]
    refinement_suggestions: List[str]
    concurs_with_selection: bool


class ArbitrationDecision(BaseModel):
    """Final synthesized arbitration decision following hypothesis and critique."""
    final_selected_model: str
    confidence: float = Field(..., ge=0.0, le=1.0)
    arbitration_summary: str
    consensus_reached: bool
    requires_fallback_to_aic: bool = False


class StructuredReasoningEngine:
    """
    Coordinates structured scientific reasoning by combining deterministic ODE statistics
    and GRU temporal evidence into a formal prompt, executing hypothesis generation,
    critique, and arbitration.
    """

    SYSTEM_PROMPT = """You are a Principal Computational Biologist and Biophysicist specializing in microbial kinetics.
Your objective is to evaluate candidate growth models (Gompertz, Logistic, Richards, Baranyi) for an empirical time-series.
You are given:
1. Deterministic Non-linear ODE regression statistics (AIC, BIC, R-squared, fitted parameters).
2. Deep Recurrent Neural (GRU) temporal evidence (lag exit point, growth rate inflection, neural model priors).

Rules:
- Strictly adhere to physical conservation laws and microbiological realism.
- Never hallucinate parameter values; cite exact values from the deterministic solver.
- Output purely structured JSON conforming to the schema."""

    def __init__(self, mode: str = "mock_deterministic"):
        """
        mode: 'mock_deterministic' for reproducible offline testing/benchmarks,
              'vllm_client' / 'api' for live HPC LLM inference.
        """
        self.mode = mode

    def build_prompt(
        self,
        ode_fits: Dict[str, Any],
        neural_evidence: Dict[str, Any],
        experiment_context: Optional[Dict[str, Any]] = None,
    ) -> str:
        """Constructs a high-context scientific prompt."""
        prompt_lines = [
            "# SCIENTIFIC CONTEXT & TRAJECTORY EVIDENCE",
            f"Experimental Duration: {experiment_context.get('duration_hours', 48.0)} hours",
            f"Assay Type: {experiment_context.get('assay_type', 'High-throughput microplate OD600 spectrophotometry')}",
            "",
            "## 1. MECHANISTIC ODE REGRESSION RESULTS (Deterministic Solver)",
        ]

        for name, fit in ode_fits.items():
            params_str = ", ".join([f"{k}={v:.4f}" for k, v in fit.get("parameters", {}).items()])
            prompt_lines.append(
                f"- Model: {name:10s} | AIC: {fit.get('aic', 0.0):8.2f} | R²: {fit.get('r_squared', 0.0):.4f} "
                f"| Converged: {fit.get('converged', False)} | Params: [{params_str}]"
            )

        prompt_lines.extend([
            "",
            "## 2. DEEP TEMPORAL EVIDENCE (Bidirectional GRU + Attention)",
            f"- Neural Model Prior: {neural_evidence.get('predicted_model_prior', 'N/A')} (Confidence: {neural_evidence.get('confidence', 0.0):.3f})",
            f"- Critical Dynamical Transition Point: {neural_evidence.get('peak_attention_time_hours', 0.0):.2f} hours",
            f"- Class Probabilities: {json.dumps(neural_evidence.get('class_probabilities', {}))}",
            "",
            "## INSTRUCTIONS",
            "Synthesize the mechanistic statistical fits with the temporal neural evidence.",
            "Account for model complexity penalties (Richards has extra shape parameter nu).",
            "Generate your hypothesis strictly following the required JSON schema.",
        ])

        return "\n".join(prompt_lines)

    def generate_hypothesis(
        self,
        ode_fits: Dict[str, Any],
        neural_evidence: Dict[str, Any],
        experiment_context: Optional[Dict[str, Any]] = None,
    ) -> ModelHypothesis:
        """Generates initial structured hypothesis."""
        if self.mode == "mock_deterministic":
            # Rank models based on joint criteria: AIC score + Neural prior alignment
            rankings: List[CandidateRanking] = []
            neural_prior = neural_evidence.get("predicted_model_prior", "")
            neural_probs = neural_evidence.get("class_probabilities", {})

            # Find best candidate
            candidates = list(ode_fits.keys())
            sorted_candidates = sorted(
                candidates,
                key=lambda m: (ode_fits[m].get("aic", 1e6) - 15.0 * neural_probs.get(m, 0.0)),
            )
            top_model = sorted_candidates[0]
            top_fit = ode_fits[top_model]

            for name in candidates:
                fit = ode_fits[name]
                prob = neural_probs.get(name, 0.25)
                plaus = min(1.0, max(0.0, float(fit.get("r_squared", 0.0) * (0.6 + 0.4 * prob))))
                rankings.append(
                    CandidateRanking(
                        model_name=name,
                        aic=float(fit.get("aic", 0.0)),
                        r_squared=float(fit.get("r_squared", 0.0)),
                        plausibility_score=round(plaus, 3),
                        primary_limitation_or_strength=(
                            "Optimal parsimony and dynamics match."
                            if name == top_model
                            else "Sub-optimal residual distribution or over-parameterization."
                        ),
                    )
                )

            return ModelHypothesis(
                selected_model=top_model,
                confidence_score=round(float(min(0.98, max(0.65, top_fit.get("r_squared", 0.9) * 0.95))), 3),
                mechanistic_rationale=(
                    f"Model {top_model} achieves lowest penalized information criterion (AIC={top_fit.get('aic', 0.0):.2f}, "
                    f"R²={top_fit.get('r_squared', 0.0):.4f}) with congruent temporal lag-phase alignment matching GRU evidence."
                ),
                temporal_features_analyzed=[
                    "Lag phase exit curvature",
                    "Inflection point growth velocity peak",
                    "Asymptotic stationary phase plateau stability",
                ],
                cited_parameters={k: float(v) for k, v in top_fit.get("parameters", {}).items()},
                candidate_rankings=rankings,
                biological_interpretation=(
                    f"The culture demonstrates a clear physiological adaptation period followed by rapid exponential biomass accumulation. "
                    f"Fitted max specific rate mu_max={top_fit.get('parameters', {}).get('mu_max', 0.5):.3f} h^-1 indicates robust metabolic efficiency."
                ),
            )
        else:
            raise NotImplementedError(f"Mode {self.mode} requires live API credentials or vLLM server.")

    def critique_hypothesis(
        self,
        hypothesis: ModelHypothesis,
        ode_fits: Dict[str, Any],
        neural_evidence: Dict[str, Any],
    ) -> CritiqueReport:
        """Adversarial critique agent evaluating the hypothesis."""
        fit = ode_fits.get(hypothesis.selected_model, {})
        flaws = []
        strengths = [
            f"Selected model {hypothesis.selected_model} matches statistical best fit.",
            "Cited parameters accurately reflect solver convergence states.",
        ]

        if fit.get("r_squared", 1.0) < 0.85:
            flaws.append("Elevated residual variance observed in exponential regime.")
        
        # Check if Richards model is selected without significant AIC improvement
        if hypothesis.selected_model == "Richards":
            gompertz_aic = ode_fits.get("Gompertz", {}).get("aic", 1e6)
            richards_aic = fit.get("aic", 1e6)
            if abs(gompertz_aic - richards_aic) < 2.0:
                flaws.append("Richards introduces extra degree of freedom (nu) with marginal delta AIC (< 2.0).")

        critique_score = 0.92 if len(flaws) == 0 else 0.78
        return CritiqueReport(
            critique_score=critique_score,
            strengths=strengths,
            potential_flaws_or_hallucinations=flaws,
            refinement_suggestions=["Confirm parameter confidence bounds across biological replicates."],
            concurs_with_selection=len(flaws) == 0 or critique_score >= 0.75,
        )

    def arbitrate(
        self,
        hypothesis: ModelHypothesis,
        critique: CritiqueReport,
        ode_fits: Dict[str, Any],
    ) -> ArbitrationDecision:
        """Final arbitration balancing hypothesis claims and critique scrutiny."""
        if critique.concurs_with_selection:
            return ArbitrationDecision(
                final_selected_model=hypothesis.selected_model,
                confidence=hypothesis.confidence_score,
                arbitration_summary=(
                    f"Consensus validated for {hypothesis.selected_model}. "
                    f"Critique confirms robust parsimony and consistency with observations."
                ),
                consensus_reached=True,
                requires_fallback_to_aic=False,
            )
        else:
            # Fallback to model with lowest AIC
            best_aic_model = min(ode_fits.keys(), key=lambda k: ode_fits[k].get("aic", 1e6))
            return ArbitrationDecision(
                final_selected_model=best_aic_model,
                confidence=0.70,
                arbitration_summary=(
                    f"Critique flagged unverified complexity in {hypothesis.selected_model}. "
                    f"Arbitration fallback executed to parsimonious AIC minimum: {best_aic_model}."
                ),
                consensus_reached=False,
                requires_fallback_to_aic=True,
            )
